# Site settings
title: LoveManatee
email: max@lovemanatee.com
description: > # this means to ignore newlines until "baseurl:"
  LoveManatee is the leading resource for manatees on the web. Learn manatee facts, find places to view and visit manatees, and discover their impact on the world around us.
baseurl: ""
url: "http://lovemanatee.com" # the base hostname & protocol for your site
twitter_username: maxpupmax
github_username:  maxthemax

# Build settings
markdown: kramdown
